### ISSUE TITLE
"Send feedback" opens invalid page

### ISSUE THREAD

**Issue by ncoleman** [smartertechnologist/SmarterBookmarks-Android#1]
I have a query and so opened "send feedback".  The screenshot shows what opened (I've deleted the names of contacts at the bottom for privacy).  It doesn't make sense to me and I don't know how to proceed.

![Screenshot_20240228-094536](https://github.com/smartertechnologist/SmarterBookmarks-Android/assets/594168/430310a4-1bee-4ba9-b4b8-89b2e4f6289e)

**Comment by smartertechnologist** [comment]
Seen. 

Can you please share the text to an email client, say Gmail and see what happens? 

Please note that the prefilled text contains basic device and app version info needed for troubleshooting. 

Thank you.

**Comment by ncoleman** [comment]
The next step is to choose my email client app and then various fields are correctly pre-filled.

Thank you Mr Dev 📨
