### ISSUE TITLE
Auto Import Database from Google Drive folder

### ISSUE THREAD

**Issue by Crunchbits** [smartertechnologist/SmarterBookmarks-Android#4]
I auto-backup my desktop browser bookmarks into html files onto a Google Drive folder and it would be very useful to access the last created version by having it automatically imported into the app.

Would be great if this was an option.

**Comment by smartertechnologist** [comment]
I've taken note of this. It's a good option. Implementing might take a while though. Thanks.

**Comment by smartertechnologist** [comment]
Hi, this has been implemented, kindly update the app. Thanks! 

PS: If there are issues, you can reopen the issue.
