### ISSUE TITLE
Remove Metadata (enhancement)

### ISSUE THREAD

**Issue by gagarwa** [smartertechnologist/SmarterBookmarks-Android#5]
Ability to remove metadata from bookmarks, and to blacklist the site when fetching metadata.  This is useful when the bookmarked link no longer matches the live site, but you want to keep it as a reference.

Example: Saved a link to a movie on X site, but now it opens 404.  You want to keep the bookmark to look for it elsewhere.

**Comment by smartertechnologist** [comment]
Hi, this is currently possible by turning off 'Auto-refresh metadata' when adding or editing a bookmark.
![Screenshot_2024-10-09-08-56-32-554_com smarter technologist android smarterbookmarks-edit](https://github.com/user-attachments/assets/1e77134e-8405-4bb9-ad83-e8a24668d73b)

**Comment by gagarwa** [comment]
That is a lot of effort to do for each bookmark, and I have many with this issue.  I also disabled auto-fetch metadata for new bookmarks, but it doesn't work sometimes (maybe it is already saved in the cache).  I did get some success by clearing the cache.

Also, it is not possible to disassociate the favicon and link URL (which are no longer accurate).  There is no way to remove the image either.  The only workaround is to link to random real site like google.com.

**Comment by smartertechnologist** [comment]
The objectives for you are (1) to disable metadata fetch completely and (2) to clear existing metadata. If so, this can be done.

**Comment by gagarwa** [comment]
Yes, (1) can be done through the settings, though it may have issues as reported above.  (2) I don't believe is possible yet, and if so, I don't know how.  (2-A) The ability to remove metadata for multiple bookmarks at once would be nice to have.  (3) The ability to blacklist certain sites from fetching metadata would be nice to have, rather than disable completely.

**Comment by smartertechnologist** [comment]
This has been implemented, kindly update to check.
