### ISSUE TITLE
Save Link Title from Source, if available (enhancement)

### ISSUE THREAD

**Issue by gagarwa** [smartertechnologist/SmarterBookmarks-Android#6]
When sharing links, the source application (like a browser) may provide the title along with the URL of the link.  Preference to save this title initially when fetching metadata is not desired and may save bandwidth.

**Comment by smartertechnologist** [comment]
I have noted this, it will be implemented as soon as possible.

**Comment by smartertechnologist** [comment]
This has been implemented.

**Comment by smartertechnologist** [comment]
I am marking it as closed.
