### ISSUE TITLE
Staggered Grid Layout

### ISSUE THREAD

**Issue by abdrhmniqbal** [smartertechnologist/SmarterBookmarks-Android#8]
Is nice to having a grid layout for bookmarks. But what if we have staggered grid to make it better viewing for visualizing image bookmark. Or maybe simply add option to full view image in grid layout without cropping the image preview.

**Comment by smartertechnologist** [comment]
That makes sense. We'll consider in the next update. Thanks

**Comment by smartertechnologist** [comment]
This is available now, please update. Thanks!

**Comment by abdrhmniqbal** [comment]
Sorry for late comment. I have downloaded the latest version, and this works. Thanks! 🎉

**Comment by smartertechnologist** [comment]
You're welcome!
